# Generated by Django 3.0.7 on 2020-06-30 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('old', 'Б/у'), ('new', 'Новый')], default='old', max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('tags', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('avatar', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
