# Generated by Django 3.0.7 on 2020-07-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200701_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
