# Generated by Django 3.0.7 on 2020-07-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200701_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AddField(
            model_name='article',
            name='seen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
