# Generated by Django 3.0.8 on 2020-07-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageBase', '0001_initial'),
        ('articles', '0004_auto_20200701_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='imageBase.ImageModel'),
        ),
    ]
