# Generated by Django 3.0.8 on 2020-07-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageBase', '0001_initial'),
        ('articles', '0005_auto_20200703_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='imageBase.ImageModel'),
        ),
    ]
